"use client"

import TodoApp from '../components/TodoApp'

export default function Home() {
  return (
    <div className='styles.container'>
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div className="flex justify-center items-center h-screen">
        <TodoApp />
      </div>
    </div>
  )
}
